<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><TargetFrameworkVersion>v4.8</TargetFrameworkVersion><OutputType>Library</OutputType><LangVersion>7.3</LangVersion></PropertyGroup>
  <ItemGroup><Reference Include="System.Web"/><Reference Include="System.ServiceModel"/><ProjectReference Include="..\Shared\Shared.vbproj"/></ItemGroup>
</Project>
